apiVersion: v1
kind: Service
metadata:
  name: xip-server
  namespace: xip
spec:
  selector:
    app: xip-service
  type: NodePort
  ports:
  - name: dns-tcp
    protocol: TCP
    port: 53
    targetPort: 53
    nodePort: 30053
  - name: dns-udp
    protocol: UDP
    port: 53
    targetPort: 53
    nodePort: 30053
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xip-service
  name: xip-service
  namespace: xip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xip-service
  template:
    metadata:
      labels:
        app: xip-service
    spec:
      containers:
      - command: ['/xip.name/xip', '-addr', ':53', '-fqdn', 'kubesphere.edge', '-ip', '192.168.100.1', '-v']
        image: dockerhub.qingcloud.com/kubeedge/xip
        imagePullPolicy: IfNotPresent
        name: xip-service
        ports:
        - containerPort: 53
          protocol: TCP
        - containerPort: 53
          protocol: UDP

